### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Haarolean** [Haarolean/gnutard-bot#11]
```
tardbot  | 2024-11-16T07:50:40.370Z ERROR 1 --- [legram Executor] o.t.t.u.DefaultBotSession                : Cannot invoke "org.telegram.telegrambots.meta.api.objects.Message.isUserMessage()" because the return value of "org.telegram.telegrambots.meta.api.objects.Update.getMessage()" is null
tardbot  |
tardbot  | java.lang.NullPointerException: Cannot invoke "org.telegram.telegrambots.meta.api.objects.Message.isUserMessage()" because the return value of "org.telegram.telegrambots.meta.api.objects.Update.getMessage()" is null
tardbot  | 	at dev.haarolean.gnutardbot.abilities.TrollingAbility.isApplicable(TrollingAbility.kt:33) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at dev.haarolean.gnutardbot.abilities.DefaultAbility$handle$1.invoke(DefaultAbility.kt:36) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at dev.haarolean.gnutardbot.abilities.DefaultAbility$handle$1.invoke(DefaultAbility.kt:36) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at dev.haarolean.gnutardbot.abilities.DefaultAbility.handle$lambda$1(DefaultAbility.kt:36) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
tardbot  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
tardbot  | 	at dev.haarolean.gnutardbot.abilities.DefaultAbility.handle(DefaultAbility.kt:37) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at dev.haarolean.gnutardbot.abilities.DefaultAbility.buildAbility$lambda$0(DefaultAbility.kt:28) ~[!/:1.0.0-SNAPSHOT]
tardbot  | 	at org.telegram.abilitybots.api.bot.BaseAbilityBot.consumeUpdate(BaseAbilityBot.java:503) ~[telegrambots-abilities-6.8.0.jar!/:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
tardbot  | 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
tardbot  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
tardbot  | 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
tardbot  | 	at org.telegram.abilitybots.api.bot.BaseAbilityBot.onUpdateReceived(BaseAbilityBot.java:256) ~[telegrambots-abilities-6.8.0.jar!/:na]
tardbot  | 	at org.telegram.abilitybots.api.bot.AbilityBot.onUpdateReceived(AbilityBot.java:55) ~[telegrambots-abilities-6.8.0.jar!/:na]
tardbot  | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
tardbot  | 	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[telegrambots-meta-6.8.0.jar!/:na]
tardbot  | 	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:312) ~[telegrambots-6.8.0.jar!/:na]
```

**Comment by Haarolean** [comment]
Fixed in 7ab44218b5aea1f3ee255c1145ee3acf7ccce763
